### PR TITLE
Add YAML file generator

### PR DESCRIPTION
**Pull request by taiki45**
Like:

```
~/.ghq/github.com/cookpad/itacho add-yaml-generator
✔ ./itacho generate-yaml -s example/book.jsonnet -o tmp/book.yaml
INFO[0000] Generated YAML file: tmp/book.yaml

~/.ghq/github.com/cookpad/itacho add-yaml-generator
✔ head tmp/book.yaml
dependencies:
- circuit_breaker:
    max_connections: 64
    max_pending_requests: 128
    max_retries: 3
  cluster_name: user-development
  connect_timeout_ms: 250
  host_header: user-service
  lb: user-app:8080
  name: user
```

@cookpad/infra @cookpad/dev-infra FYI

### CODE REVIEW

**Comment by eagletmt** [comment]
What is the purpose of this subcommand?
It seems equivalent to `jsonnet example/book.jsonnet -o tmp/book.yaml` because a valid JSON string is also a valid YAML string.

**Comment by taiki45** [comment]
The purpose is to make an altenative feature of the previous [kumonos sub command](https://github.com/cookpad/kumonos/blob/ae12152b4dc09a8e46e4fa40afed9598daeab839/exe/kumonos#L78-L87) which evaluate Jsonnet file and convert into YAML file, which we use in the test phase of service mesh repo.

I forgot the jsonnet command and it seems equivalent excluding that it generates JSON file not YAML file. But, I found we can switch from YAML file to JSON file in the test phase of service mesh repo, so we don't need this.

@eagletmt Any thoughts?

**Comment by eagletmt** [comment]
If the test phase needs a YAML file, `jsonnet` CLI is enough because a valid JSON file is also a valid YAML file (in practice) and you should not add this subcommand to keep it simple.
https://yaml.org/spec/1.2/spec.html#id2759572

But if you suppose an environment without `jsonnet` CLI installed, adding this subcommand could be acceptable.

**Comment by taiki45** [comment]
>a valid JSON file is also a valid YAML file (in practice) 

Oh... I didn't know that... Oh.. So this PR should be closed and we will use jsonnet CLI tool instead of this.

**Pull request closed without merging**
