### PR TITLE
Update go version

### PR DESCRIPTION
**Pull request by ryojiro**
Update golang and ruby versions. Also bundle update for fixing security alert https://github.com/cookpad/itacho/network/alert/test/app/Gemfile.lock/rack/open .

I confirmed that `make` and `make integration_test` commands work in my local environment.

@cookpad/infra please check this PR

### CODE REVIEW

**Comment by eagletmt** [comment]
Split this PR into "Update Go" and "Update Ruby".
Updating Ruby version and gems only affects test suites, but updating Go version and modules affects production (even if it compiles successfully).

**Comment by ryojiro** [comment]
It makes sense. I divide parts of updating ruby version into another PR https://github.com/cookpad/itacho/pull/11 . So I will change this PR only parts of updating go version.

**Comment by ryojiro** [comment]
There are many changes.
However I only changed go version https://github.com/cookpad/itacho/pull/10/commits/83625efc2c7159c20a22db759d2f5be61e6454f4 and executed `go mod {download,vendor,tidy}`.

@cookpad/infra please review this PR again.

**Comment by ryojiro** [comment]
-> https://github.com/cookpad/itacho/pull/13

**Pull request closed without merging**
